name: somnus_sync
description: Background Health Connect sleep sync APK for Somnus Telegram bot.
publish_to: "none"

version: 0.1.2+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_health_connect: ^1.2.3
  http: ^1.2.2
  shared_preferences: ^2.3.2
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
